"""baseline: infrastructure and candidate memory

Revision ID: b28c13367666
Revises: 
Create Date: 2026-07-19 12:14:38.187931

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b28c13367666'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_sha256'), ['sha256'], unique=False)

    op.create_table('domain_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_event_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_event_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_event_event_type'), ['event_type'], unique=False)

    op.create_table('llm_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_ref', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('workflow_id', sa.String(length=64), nullable=True),
    sa.Column('application_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_run_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_run_task'), ['task'], unique=False)

    op.create_table('candidate_fact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_span', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('reuse_permitted', sa.Boolean(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['candidate_fact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_fact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_fact_confirmed'), ['confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_fact_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_fact_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_fact_superseded_by'), ['superseded_by'], unique=False)

    op.create_table('candidate_story',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('obstacles', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('learned', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('shareability', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_story', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_story_confirmed'), ['confirmed'], unique=False)

    op.create_table('resume',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    with op.batch_alter_table('candidate_story', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_story_confirmed'))

    op.drop_table('candidate_story')
    with op.batch_alter_table('candidate_fact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_fact_superseded_by'))
        batch_op.drop_index(batch_op.f('ix_candidate_fact_section'))
        batch_op.drop_index(batch_op.f('ix_candidate_fact_key'))
        batch_op.drop_index(batch_op.f('ix_candidate_fact_confirmed'))

    op.drop_table('candidate_fact')
    with op.batch_alter_table('llm_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_run_task'))
        batch_op.drop_index(batch_op.f('ix_llm_run_created_at'))
        batch_op.drop_index(batch_op.f('ix_llm_run_application_id'))

    op.drop_table('llm_run')
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_domain_event_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_domain_event_aggregate_id'))

    op.drop_table('domain_event')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifact_kind'))

    op.drop_table('artifact')
    # ### end Alembic commands ###
