"""interview_question table

Revision ID: f3778be70360
Revises: b28c13367666
Create Date: 2026-07-19 16:37:48.597648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3778be70360'
down_revision: Union[str, Sequence[str], None] = 'b28c13367666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'key', name='uq_interview_question_slot')
    )
    with op.batch_alter_table('interview_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_question_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_question_status'))

    op.drop_table('interview_question')
    # ### end Alembic commands ###
